Lineplots of extraterrestrial and sea level solar radiation in mW instead of W:
```{r}
library(readxl)
library(tidyverse)

# load data frames
solar <- read_xls("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/solar radiation/e490_00a_amo.xls")
sealevel <- read_xls("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/solar radiation/astmg173.xls", sheet = "SMARTS2")

solar <- solar %>% mutate(Type = "Extraterrestrial", Wavelength = `Wavelength, nm`, Irradiance = `Wehrli, W/m2/nm`) %>%
  select(Type, Wavelength, Irradiance)
sealevel <- sealevel %>% mutate(Type = "Sea Level", Wavelength = `Wvlgth nm`, Irradiance = `Global tilt  W*m-2*nm-1`) %>%
  select(Type, Wavelength, Irradiance)

# Conversion to mW/cm^2/nm
solar_converted <- solar %>% mutate(Irradiance_mW = Irradiance * 0.1)
sealevel_converted <- sealevel %>% mutate(Irradiance_mW = Irradiance * 0.1)

# Combine the converted datasets
combined_converted <- rbind(solar_converted, sealevel_converted)

# Display the combined dataset
print(combined_converted)

ymax <- max(combined_converted$Irradiance_mW, na.rm = TRUE)

cplot <- ggplot(data = combined_converted, aes(x = Wavelength, y = Irradiance_mW, group = Type, color = Type)) +
  geom_line() +
  scale_x_continuous(breaks = seq(200, 700, by = 100), limits = c(200, 710), expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 0.22), expand = c(0,0)) +
  labs(x = "Wavelength [nm]",
       y = expression("Spectral Irradiance [mW/cm"^{2}*"/nm]")) +
  geom_vline(xintercept = c(280, 315, 400), linetype = "dashed", color = "black", linewidth = 0.5) +
  geom_text(aes(x = 240, y = ymax, label = "UV-C"), size = 3, family = "Arial", color = "black") +
  geom_text(aes(x = 297.5, y = ymax, label = "UV-B"), size = 3, family = "Arial", color = "black") +
  geom_text(aes(x = 357.5, y = ymax, label = "UV-A"), size = 3, family = "Arial", color = "black") +
  geom_text(aes(x = 550, y = ymax, label = "Visible"), size = 3, family = "Arial", color = "black") +
  scale_color_manual(values = c("Extraterrestrial" = "#D55E00", "Sea Level" = "#005AB5")) +
  theme_classic() +
  theme(axis.text = element_text(size = 10), # Increase tick label font size
        axis.title.x = element_text(size = 10, margin = margin(t = 10)), # Increase X axis label font size and add space
        axis.title.y = element_text(size = 10, margin = margin(r = 15)),  # Increase Y axis label font size and add space
        legend.position = "none" # Hide the legend
       )

cplot

ggsave(filename = "combined_solarplot_5.svg", plot = cplot, unit = "mm", width = 150, height = 100, dpi = 600)

```
TLVs, erythema, and NMSC in one plot
```{r}
library(tidyverse)
library(readxl)
library(gridExtra)
library(scales)

# loading data frames for ACGIH TLVs
tlv <- read_xlsx("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/action_spectra_and_tlv_data.xlsx", sheet = "TLV")
tlv_skin <- read_xlsx("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/action_spectra_and_tlv_data.xlsx", sheet = "TLV_skin")

# Load data into data frame erythema
erythema <- read_xlsx("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/action_spectra_and_tlv_data.xlsx", sheet = "action_spectra")

# Load data into data frame nmsc
nmsc <- read_xlsx("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/action_spectra_and_tlv_data.xlsx", sheet = "action_spectra")

# renaming columns to make them easier to handle
tlv <- tlv %>%
  rename("wavel" = "Wavelength (nm)",
         "tlv" = "TLV (mJ/cm^2)",
         "rse" = "Relative Spectral Effectiveness")

tlv_skin <- tlv_skin %>%
  rename("wavel" = "Wavelength (nm)",
         "tlv" = "TLV (mJ/cm^2)",
         "rse" = "Relative Spectral Effectiveness")

# Combine data into one data frame
combined_data <- bind_rows(
  tlv %>% mutate(Type = "tlv"),
  tlv_skin %>% mutate(Type = "tlv_skin"),
  erythema %>% mutate(Type = "erythema"),
  nmsc %>% mutate(Type = "nmsc")
)

# reducing the erythema and NMSC action spectra by a constant to allow for an accurate comparison
erythema$erythema_scaled <- erythema$erythema / max(erythema$erythema) * 0.3
nmsc$nmsc_scaled <- nmsc$nmsc / max(nmsc$nmsc) * 0.15

# Create combined plot
combined_plot <- ggplot() +
  geom_line(data = tlv, aes(x = wavel, y = rse, color = "TLV", linetype = "TLV")) +
    geom_line(data = tlv_skin, aes(x = wavel, y = rse, color = "TLV_skin", linetype = "TLV_skin")) +
  geom_line(data = erythema, aes(x = wavel, y = erythema_scaled, color = "Erythema", linetype = "Erythema")) +
  geom_line(data = nmsc, aes(x = wavel, y = nmsc_scaled, color = "NMSC", linetype = "NMSC")) +
  labs(x = "Wavelength [nm]", y = "Relative Spectral Effectiveness") +
  scale_x_continuous(limits = c(200, 400), breaks = seq(from = 200, to = 400, by = 50)) +
  scale_y_log10(limits = c(0.00003, 1), labels = number_format(accuracy = 0.0001, big.mark = ",")) +
  scale_color_manual(values = c("TLV" = "black","TLV_skin" = "black", "Erythema" = "#D55E00", "NMSC" = "#0072B2"),
                     name = "",
                     labels = c("ACGIH UV (eyes)", "ACGIH UV (skin)", "CIE erythema", "CIE NMSC"),
                     breaks = c("TLV", "TLV_skin", "Erythema", "NMSC")) +
  scale_linetype_manual(values = c("TLV" = "solid", "TLV_skin" = "dotdash", "Erythema" = "dashed", "NMSC" = "dotted"),
                        name = "",
                        labels = c("ACGIH UV (eyes)", "ACGIH UV (skin)", "CIE erythema", "CIE NMSC"),
                        breaks = c("TLV", "TLV_skin", "Erythema", "NMSC")) +
  theme_classic() +
  theme(
    legend.position = c(0.65, 0.5), # Adjust the x and y values for the desired position
    legend.justification = c(0, 0),
    legend.background = element_rect(fill = "transparent", color = "transparent"),
    legend.box.background = element_rect(fill = "transparent", color = "transparent"),
    axis.text = element_text(size = 10), # Increase tick label font size
    axis.title.x = element_text(size = 10, margin = margin(t = 10)), # Increase X axis label font size and add space
    axis.title.y = element_text(size = 10, margin = margin(r = 15))  # Increase Y axis label font size and add space
    )

combined_plot

ggsave("tlv_erythema_nmsc_one_panel.png", combined_plot, width = 120, height = 75, unit = "mm", dpi = 600)
```

Panel plot of TLVs, erythema and NMSC action spectra
```{r}
library(tidyverse)
library(readxl)
library(gridExtra)
library(cowplot)
library(scales)

# loading data frames for ACGIH TLVs
tlv <- read_xlsx("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/action_spectra_and_tlv_data.xlsx", sheet = "TLV")
tlv_skin <- read_xlsx("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/action_spectra_and_tlv_data.xlsx", sheet = "TLV_skin")

# check column names in the data frames
colnames(tlv)
colnames(tlv_skin)

# renaming columns to make them easier to handle
tlv <- tlv %>%
  rename("wavel" = "Wavelength (nm)",
         "tlv" = "TLV (mJ/cm^2)",
         "rse" = "Relative Spectral Effectiveness")

tlv_skin <- tlv_skin %>%
  rename("wavel" = "Wavelength (nm)",
         "tlv" = "TLV (mJ/cm^2)",
         "rse" = "Relative Spectral Effectiveness")

tlv_plot <- ggplot() +
  geom_line(data = tlv, aes(x = wavel, y = rse, linetype = "TLV", color = "TLV")) +
  geom_line(data = tlv_skin, aes(x = wavel, y = rse, linetype = "TLV (skin)", color = "TLV (skin)")) +
  geom_text(aes(x = 210, y = 1, label = "a"), size = 5, family = "Arial", color = "black") +
  labs(x = "Wavelength [nm]",
       y = "Relative Spectral Effectiveness") +
  scale_x_continuous(limits = c(200, 400), breaks = seq(from = 200, to = 400, by = 50)) +
  scale_y_log10(limits = c(0.00003, 1), labels = number_format(accuracy = 0.0001, big.mark = ",")) +
  scale_linetype_manual(values = c("TLV" = "solid", "TLV (skin)" = "dashed"),
                        name = "",
                        labels = c("TLV\u00AE (eyes)", "TLV\u00AE (skin)")) +
  scale_color_manual(values = c("TLV" = "black", "TLV (skin)" = "black"),
                     name = "",
                     labels = c("TLV\u00AE (eyes)", "TLV\u00AE (skin)")) +
  theme_classic() +
  theme(
    legend.position = c(0.6, 0.5), # Adjust the x and y values for the desired position
    legend.justification = c(0, 0),
    legend.background = element_rect(fill = "transparent", color = "transparent"),
    legend.box.background = element_rect(fill = "transparent", color = "transparent"),
    axis.text = element_text(size = 10), # Increase tick label font size
    axis.title.x = element_text(size = 10, margin = margin(t = 10)), # Increase X axis label font size and add space
    axis.title.y = element_text(size = 10, margin = margin(r = 15)),  # Increase Y axis label font size and add space
    plot.margin = margin(0.2, 0.2, 0.2, 0.2, "cm")
    )

# Load data into data frame erythema
erythema <- read_xlsx("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/action_spectra_and_tlv_data.xlsx", sheet = "action_spectra")

# Create linear scale plot
erythema_plot <- ggplot(erythema, aes(x = wavel, y = erythema)) +
  geom_line(linetype = "solid", color = "#D55E00") +
  geom_text(aes(x = 210, y = 1, label = "b"), size = 5, family = "Arial", color = "black") +
  labs(x = "Wavelength [nm]",
       y = "Relative Spectral Effectiveness") +
  scale_x_continuous(limits = c(200, 400)) +
  scale_y_log10(limits = c(0.00003, 1), labels = number_format(accuracy = 0.0001, big.mark = ",")) +
  theme_classic() +
  theme(axis.text = element_text(size = 10), # Increase tick label font size
        axis.title.x = element_text(size = 10, margin = margin(t = 10)), # Increase X axis label font size and add space
        axis.title.y = element_text(size = 10, margin = margin(r = 15)),  # Increase Y axis label font size and add space
        plot.margin = margin(0.2, 0.2, 0.2, 0.2, "cm")
       )

# Load data into data frame nmsc
nmsc <- read_xlsx("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/action_spectra_and_tlv_data.xlsx", sheet = "action_spectra")

# Create log scale plot
log_plot <- ggplot(nmsc, aes(x = wavel, y = nmsc)) +
  geom_line(linetype = "solid", color = "#0072B2") +
  geom_text(aes(x = 210, y = 1, label = "c"), size = 5, family = "Arial", color = "black") +
  labs(x = "Wavelength [nm]",
       y = "Relative Spectral Effectiveness") +
  scale_x_continuous(limits = c(200, 400)) +
  scale_y_log10(limits = c(0.00003, 1), labels = number_format(accuracy = 0.0001, big.mark = ",")) +
  theme_classic() +
  theme(axis.text = element_text(size = 10), # Increase tick label font size
        axis.title.x = element_text(size = 10, margin = margin(t = 10)), # Increase X axis label font size and add space
        axis.title.y = element_text(size = 10, margin = margin(r = 15)),  # Increase Y axis label font size and add space
        plot.margin = margin(0.2, 0.2, 0.2, 0.2, "cm")
       )

# Arrange the plots
plot_grid(tlv_plot, erythema_plot, log_plot, ncol = 1, align = 'v')


ggsave("tlv_erythema_nmsc_panel_plot_log_scale.png", plot_grid(tlv_plot, erythema_plot, log_plot, ncol = 1, align = 'v'), width = 100, height = 200, unit = "mm", dpi = 600)


```


Protein absorption plot; data available from https://github.com/lennijusten/protein-absorbance ; See file "data-table.csv"
```{r}
library(tidyverse)

# protein absorption data frame
pa <- read.csv("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/protein absorption by lenni/data-table.csv")

str(pa) # check column names

plot <- ggplot(pa, aes(x = Wavelength, y = Mean.Absorption.Coefficient)) +
  geom_line() +
  geom_ribbon(aes(ymin = Mean.Absorption.Coefficient - Absorption.Coefficient.Std.Dev, ymax = Mean.Absorption.Coefficient + Absorption.Coefficient.Std.Dev), alpha=0.2) +
  scale_x_continuous(breaks = seq(from = 200, to = 320, by = 20)) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Wavelength [nm]",
       y = "Absorption coefficient [ml/mg x cm]") +
  theme_classic() +
  theme(axis.text = element_text(size = 10), # Increase tick label font size
        axis.title.x = element_text(size = 10, margin = margin(t = 10)), # Increase X axis label font size and add space
        axis.title.y = element_text(size = 10, margin = margin(r = 15))  # Increase Y axis label font size and add space
       )

plot

ggsave("protein_absorption.png", plot, unit = "mm", width = 100, height = 75, dpi = 600)
```
DNA absorption plot; data available from https://github.com/lennijusten/DNA-absorbance/ ; See file "data-table.csv"
```{r}
library(tidyverse)
library(readxl)
library(gridExtra)
library(cowplot)
library(scales)

# protein absorption data frame
pa <- read.csv("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/protein absorption by lenni/data-table.csv")

str(pa) # check column names

pa_plot <- ggplot(pa, aes(x = Wavelength, y = Mean.Absorption.Coefficient)) +
  geom_line() +
  geom_ribbon(aes(ymin = Mean.Absorption.Coefficient - Absorption.Coefficient.Std.Dev, ymax = Mean.Absorption.Coefficient + Absorption.Coefficient.Std.Dev), alpha=0.2) +
  geom_text(aes(x = 190, y = 35, label = "a"), size = 5, family = "Arial", color = "black") +
  scale_x_continuous(limits = c(190, 320), breaks = seq(from = 200, to = 320, by = 20)) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Wavelength [nm]",
       y = "Absorption coefficient [ml/mg x cm]") +
  theme_classic() +
  theme(axis.text = element_text(size = 10), # Increase tick label font size
        axis.title.x = element_text(size = 10, margin = margin(t = 10)), # Increase X axis label font size and add space
        axis.title.y = element_text(size = 10, margin = margin(r = 15))  # Increase Y axis label font size and add space
       )

# DNA absorption data frame
da <- read.csv("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/DNA-absorbance-master/data-table.csv")

str(da) # check column names

da_plot <- ggplot(da) +
  geom_line(aes(x = Wavelength, y = Adenine, color = "Adenine", linetype = "Adenine")) +
  geom_line(aes(x = Wavelength, y = Cytosine, color = "Cytosine", linetype = "Cytosine")) +
  geom_line(aes(x = Wavelength, y = Guanine, color = "Guanine", linetype = "Guanine")) +
  geom_line(aes(x = Wavelength, y = Thymine, color = "Thymine", linetype = "Thymine")) +
  geom_text(aes(x = 190, y = 0.0001, label = "b"), size = 5, family = "Arial", color = "black") +
  scale_x_continuous(limits = c(190, 320), breaks = seq(from = 200, to = 320, by = 20)) +
  scale_y_continuous(expand = c(0,0), labels = number_format(accuracy = 0.00001, big.mark = ",")) +
  labs(x = "Wavelength [nm]",
       y = "Absorption coefficient [ml/mg x cm]") +
  scale_color_manual(values = c("Adenine" = "black", "Cytosine" = "#0072B2", "Guanine" = "#F0E442", "Thymine" = "#D55E00"),
                     name = "",
                     labels = c("Adenine", "Cytosine", "Guanine", "Thymine")) +
  scale_linetype_manual(values = c("Adenine" = "solid", "Cytosine" = "dotted", "Guanine" = "dashed", "Thymine" = "dotdash"),
                        name = "",
                        labels = c("Adenine", "Cytosine", "Guanine", "Thymine")) +
  theme_classic() +
  theme(legend.position = c(0.7, 0.5),
        legend.justification = c(0, 0),
        legend.background = element_rect(fill = "transparent", color = "transparent"),
        legend.box.background = element_rect(fill = "transparent", color = "transparent"),
        axis.text = element_text(size = 10), 
        axis.title.x = element_text(size = 10, margin = margin(t = 10)), 
        axis.title.y = element_text(size = 10, margin = margin(r = 15))  
       )

# Arrange the plots
plot_grid(pa_plot, da_plot, ncol = 1, align = 'v')


ggsave("protein_and_dna_absorption.png", plot_grid(pa_plot, da_plot, ncol = 1, align = 'v'), width = 130, height = 150, unit = "mm", dpi = 600)
```


Skin penetration depth plot (further edited in Biorender)
```{r}
library(tidyverse)
library(readxl)

# maximal observed depth of CPDs in RHE skin models data frame; data is from Zwicker et al. 2022
cpd <- read_xlsx("/Users/max.goerlitz/Dropbox/1 Projects/SecureBio/LWL safety/Figures/skin penetration/Maximal observed depth of CPDs in RHEs based on data from Zwicker et al. 2022.xlsx")

str(cpd) # show structure of the data frame

# Gather columns into rows, calculate mean and standard error
mean_values <- cpd %>%
  gather("Wavelength and dose", "Values", everything()) %>%
  group_by(`Wavelength and dose`) %>%
  summarise(Mean = mean(Values, na.rm = TRUE) + 17,  # Add 17 to each mean value, since in the paper they report that "The measured SC thickness was subtracted on every position" and "The mean SC thickness of RHEs was (17±4.3) µm"
            SEM = sd(Values, na.rm = TRUE) / sqrt(sum(!is.na(Values))))

mean_values # display new data set

penplot <- ggplot(data = mean_values, aes(x = `Wavelength and dose`, y = Mean)) +
  geom_point() +
  scale_y_reverse(limits = c(80, -5), breaks = seq(0,80, by = 10)) + # Set y-axis limits to include 0
  scale_x_discrete(position = "top", # Move the x-axis to the top
                   labels = c(expression("222 nm (150 mJ/cm"^2*")"),
                              expression("233 nm (80 mJ/cm"^2*")"),
                              expression("UV-B (7.5 mJ/cm"^2*")"))) +
  geom_hline(yintercept = c(17, 37+17, 50+17), linetype = "dotted", color = "grey30") + # Add dotted horizontal lines (for the sake of accurately creating the figure in biorender); adding the mean stratum corneum thickness of 17µm to the viable epidermal thickness
  labs(x = NULL,
       y = "Maximal observed depth of CPDs [µm]") +
  theme_classic() +
  theme(axis.title.y = element_text(size = 10, margin = margin(r = 15), face="bold"),  # Increase Y axis label font size and add space
        axis.text = element_text(size = 10), # Increase tick label font size
        axis.line.x = element_line(colour = "black"), # Add a solid x-axis line
        axis.line.y = element_line(colour = "black"), # Add a solid y-axis line
        axis.ticks.y = element_line(colour = "black"), # Add y-axis tick marks
        axis.ticks.x = element_line(colour = "black"), # Add x-axis tick marks
        axis.ticks.length = unit(0.15, "cm"),  # Adjust the length of tick marks
        ) 

penplot

ggsave(filename = "skin_pen_2.svg", plot = penplot, units = "mm", width = 140, height = 100, bg = "transparent")
```

